(() => {
  "use strict";
  const DB = "./assets/articles.json";
  const BASE_SITE = "https://trendrader.space";
  const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const normalizeArticle=a=>({...a,title:String(a?.title||a?.headline||"").trim(),desc:String(a?.desc||a?.description||a?.excerpt||a?.dek||"").trim(),image:String(a?.image||a?.imageUrl||a?.featuredImage||"").trim(),category:String(a?.category||a?.meta||"News").trim(),subcategory:String(a?.subcategory||"").trim(),tag:String(a?.tag||a?.contentType||"News").trim(),author:String(a?.author||"TrendRader Editorial").trim(),date:a?.date||a?.publishedAt||a?.datePublished||a?.createdAt||"",slug:String(a?.slug||"").trim(),url:String(a?.url||"").trim(),delta:String(a?.delta||"").trim(),modified:a?.modified||a?.dateModified||a?.date||""});
  const isPublished=a=>{if(!a?.title)return false;const status=String(a.status||a.state||"").toLowerCase();if(["draft","unpublished","archived","deleted"].includes(status))return false;if(a.page&&String(a.page).toLowerCase()!=="news")return false;return Boolean(a.slug||a.url)};
  const sort=a=>[...a].sort((x,y)=>new Date(y.date||0)-new Date(x.date||0));
  const articleUrl=a=>a.url?(a.url.startsWith("http")||a.url.startsWith("/")?a.url:`../${a.url.replace(/^\.\//,"")}`):`../articles/${encodeURIComponent(a.slug)}.html`;
  const formatDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"Recently published":new Intl.DateTimeFormat("en-NG",{day:"numeric",month:"long",year:"numeric"}).format(d)};
  const readTime=(a,text="")=>{const n=Number(a.readTime);if(Number.isFinite(n)&&n>0)return Math.round(n);return Math.max(1,Math.round(text.trim().split(/\s+/).filter(Boolean).length/200)||1)};
  const setMeta=(s,v)=>{const e=$(s);if(e&&v)e.setAttribute("content",v)};
  const getSlug=()=>{const q=new URLSearchParams(location.search).get("slug");if(q)return decodeURIComponent(q);const p=location.pathname.split("/").filter(Boolean),f=p[p.length-1]||"";return f.endsWith(".html")&&f!=="article.html"?f.replace(/\.html$/i,""):""};
  const safeBody=html=>{const t=document.createElement("template");t.innerHTML=String(html||"");t.content.querySelectorAll("script,style,object,embed,form,iframe").forEach(n=>n.remove());t.content.querySelectorAll("[onload],[onclick],[onerror],[onmouseover],[onfocus],[onmouseenter]").forEach(n=>[...n.attributes].forEach(a=>/^on/i.test(a.name)&&n.removeAttribute(a.name)));return t.innerHTML};
  function inline(v,attrs={}){let t=escapeHtml(v);if(attrs.bold)t=`<strong>${t}</strong>`;if(attrs.italic)t=`<em>${t}</em>`;if(attrs.underline)t=`<u>${t}</u>`;if(attrs.strike)t=`<s>${t}</s>`;if(attrs.link&&/^https?:\/\//i.test(attrs.link))t=`<a href="${escapeHtml(attrs.link)}" rel="noopener noreferrer nofollow">${t}</a>`;return t}
  function deltaToHtml(delta){if(!delta||!Array.isArray(delta.ops))return"";let html="",line="",list=null;const close=()=>{if(list){html+=`</${list}>`;list=null}};for(const op of delta.ops){if(typeof op.insert==="object"&&op.insert.image){html+=`<figure><img src="${escapeHtml(op.insert.image)}" alt="TrendRader article image" loading="lazy" decoding="async"><figcaption>TrendRader editorial image</figcaption></figure>`;continue}if(typeof op.insert!=="string")continue;const parts=op.insert.split("\n");parts.forEach((part,i)=>{if(part)line+=inline(part,op.attributes||{});if(i===parts.length-1)return;const a=op.attributes||{};const block=a.header?`h${Math.min(3,Math.max(2,Number(a.header)))}`:a.blockquote?"blockquote":a.list==="ordered"?"ol":a.list==="bullet"?"ul":null;if(block==="ol"||block==="ul"){if(list!==block){close();list=block;html+=`<${block}>`}html+=`<li>${line}</li>`}else{close();if(block==="blockquote")html+=`<blockquote><p>${line}</p></blockquote>`;else if(block)html+=`<${block}>${line}</${block}>`;else if(line.trim())html+=`<p>${line}</p>`}line=""})}close();if(line.trim())html+=`<p>${line}</p>`;return html}
  async function fetchJson(path){const r=await fetch(`${path}${path.includes("?")?"&":"?"}v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`${path} returned HTTP ${r.status}.`);return r.json()}
  async function resolve(){const slug=getSlug();const payload=await fetchJson(DB);const raw=Array.isArray(payload)?payload:Array.isArray(payload.articles)?payload.articles:Array.isArray(payload.items)?payload.items:[];const articles=sort(raw.map(normalizeArticle).filter(isPublished));const current=slug?articles.find(a=>a.slug===slug||a.url.endsWith(`${slug}.html`)):articles[0];if(!current)throw new Error("No published TrendRader article matches this URL.");let body="";if(current.bodyHtml||current.content||current.body)body=safeBody(current.bodyHtml||current.content||current.body);else if(current.delta){try{const deltaPath=current.delta.startsWith("http")?current.delta:`${location.pathname.includes("/articles/")?"../":"./"}${current.delta.replace(/^\.\//,"")}`;body=deltaToHtml(await fetchJson(deltaPath))}catch(e){console.warn("TrendRader delta load failed",e)}}return{article:current,articles,body}}
  function updateSchema(article,canonical,read){
    $$('script[type="application/ld+json"]').forEach(n=>{if(/\{\{/.test(n.textContent||""))n.remove()});
    const schema={"@context":"https://schema.org","@type":"NewsArticle","@id":`${canonical}#article`,headline:article.title,description:article.desc,url:canonical,inLanguage:"en-NG",image:article.image?[article.image]:[],datePublished:article.date,dateModified:article.modified||article.date,author:{"@type":"Organization",name:article.author||"TrendRader Editorial",url:BASE_SITE},publisher:{"@type":"Organization",name:"TrendRader",url:BASE_SITE,logo:{"@type":"ImageObject",url:`${BASE_SITE}/assets/logo.svg`}},articleSection:article.subcategory?`${article.category} / ${article.subcategory}`:article.category,keywords:Array.isArray(article.keywords)?article.keywords.join(", "):String(article.keywords||""),mainEntityOfPage:{"@type":"WebPage","@id":canonical},isAccessibleForFree:true,timeRequired:`PT${read}M`};
    const node=document.createElement("script");node.type="application/ld+json";node.textContent=JSON.stringify(schema);document.head.appendChild(node);
  }
  function buildOutline(){const o=$("#storyOutline"),b=$("#articleBody");if(!o||!b)return;const hs=$$("h2,h3",b);o.innerHTML=hs.slice(0,8).map((h,i)=>{if(!h.id)h.id=`section-${i+1}`;return `<a href="#${escapeHtml(h.id)}"><span>${String(i+1).padStart(2,"0")}</span>${escapeHtml(h.textContent)}</a>`}).join("")||`<span class="outline-empty">Published story</span>`}
  function relatedScore(current,a){const words=s=>new Set((`${s.title} ${s.desc} ${s.category} ${s.subcategory} ${Array.isArray(s.keywords)?s.keywords.join(" "):s.keywords||""}`).toLowerCase().match(/[a-z0-9]{4,}/g)||[]);const c=words(current),x=words(a);let overlap=0;x.forEach(w=>c.has(w)&&overlap++);return overlap*2+(a.category.toLowerCase()===current.category.toLowerCase()?8:0)+(a.subcategory&&a.subcategory.toLowerCase()===current.subcategory.toLowerCase()?8:0)}
  function renderRelated(articles,current){const grid=$("#relatedGrid");if(!grid)return;const list=articles.filter(a=>a.slug!==current.slug).sort((a,b)=>relatedScore(current,b)-relatedScore(current,a)||new Date(b.date)-new Date(a.date)).slice(0,3);grid.innerHTML=list.map((a,i)=>`<a class="related-card" href="${escapeHtml(articleUrl(a))}"><div class="related-image">${a.image?`<img src="${escapeHtml(a.image)}" alt="${escapeHtml(a.imageAlt||a.title)}" loading="lazy" decoding="async" width="1000" height="625">`:''}<span>${String(i+1).padStart(2,"0")}</span></div><div class="related-meta"><span>${escapeHtml(a.tag)}</span><i></i><span>${readTime(a)} min</span></div><h3>${escapeHtml(a.title)}</h3><div class="related-arrow">↗</div></a>`).join("")||`<p class="related-empty">No additional published stories yet.</p>`}
  function hydrate({article,articles,body}){
    const canonical=article.url?(article.url.startsWith("http")?article.url:`${BASE_SITE}/${article.url.replace(/^\//,"")}`):`${BASE_SITE}/articles/${article.slug}.html`;
    const read=readTime(article,body.replace(/<[^>]+>/g," "));
    document.title=`${article.seoTitle||article.title} — TrendRader`;
    setMeta('meta[name="description"]',article.desc);setMeta('meta[name="author"]',article.author);setMeta('meta[property="og:title"]',article.seoTitle||article.title);setMeta('meta[property="og:description"]',article.desc);setMeta('meta[property="og:url"]',canonical);setMeta('meta[property="og:image"]',article.image);setMeta('meta[property="og:image:alt"]',article.imageAlt||article.title);setMeta('meta[name="twitter:title"]',article.seoTitle||article.title);setMeta('meta[name="twitter:description"]',article.desc);setMeta('meta[name="twitter:image"]',article.image);setMeta('meta[name="twitter:image:alt"]',article.imageAlt||article.title);const can=$('link[rel="canonical"]');if(can)can.href=canonical;
    const set=(sel,val)=>{const e=$(sel);if(e&&val)e.textContent=val};set(".kicker-label",article.tag);set(".article-kicker > span:last-child",article.subcategory?`${article.category} / ${article.subcategory}`:article.category);set(".article-title",article.title);set(".article-dek",article.desc);set(".author strong",article.author);set(".author-details span","TrendRader Editorial");const metas=$$(".meta-item strong");if(metas[0])metas[0].textContent=formatDate(article.date);if(metas[1])metas[1].textContent=`${read} min`;
    const hero=$("#heroImage");if(hero&&article.image){hero.src=article.image;hero.alt=article.imageAlt||article.title;hero.removeAttribute("data-template-image")}else if(hero){hero.closest("figure")?.remove()}
    const b=$("#articleBody");if(b&&body){const tags=$("#articleTags");b.innerHTML=body;if(tags)b.appendChild(tags)}
    const initials=article.author.split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"T";$("#authorAvatar")?.replaceChildren(document.createTextNode(initials));$("#authorAvatarLarge")?.replaceChildren(document.createTextNode(initials));set("#authorName",article.author);if(article.authorBio)set("#authorBio",article.authorBio);
    const tags=$("#articleTags"), keywords=Array.isArray(article.keywords)?article.keywords:String(article.keywords||"").split(",").map(x=>x.trim()).filter(Boolean);if(tags&&keywords.length)tags.innerHTML=`<span>Topics</span>${keywords.slice(0,8).map(k=>`<a href="../index.html#latest">${escapeHtml(k)}</a>`).join("")}`;
    buildOutline();renderRelated(articles,article);updateSchema(article,canonical,read);
  }
  function navigation(){const m=$("#menuToggle"),n=$("#mobileNav");m?.addEventListener("click",()=>{const open=n.classList.toggle("open");m.setAttribute("aria-expanded",String(open))});$$('.mobile-nav a').forEach(a=>a.addEventListener("click",()=>{n.classList.remove("open");m.setAttribute("aria-expanded","false")}))}
  function scroll(){const p=$("#progressBar"),h=$("#siteHeader");const u=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(p)p.style.width=`${max>0?scrollY/max*100:0}%`;h?.classList.toggle("scrolled",scrollY>12)};addEventListener("scroll",u,{passive:true});u()}
  function share(){const modal=$("#shareModal"),open=()=>{modal?.classList.add("open");modal?.setAttribute("aria-hidden","false")},close=()=>{modal?.classList.remove("open");modal?.setAttribute("aria-hidden","true")};$("#shareTop")?.addEventListener("click",open);$("#shareRail")?.addEventListener("click",open);$("#closeShare")?.addEventListener("click",close);$("#shareBackdrop")?.addEventListener("click",close);$$('[data-share]').forEach(b=>b.addEventListener("click",async()=>{const type=b.dataset.share,url=location.href,title=document.title;if(type==="copy"){try{await navigator.clipboard.writeText(url);$("#shareMessage").textContent="Link copied."}catch{$("#shareMessage").textContent=url}return}const target=type==="x"?`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(url)}`:`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;window.open(target,"share","width=700,height=600,noopener,noreferrer") }));addEventListener("keydown",e=>e.key==="Escape"&&close())}
  function lightbox(){const box=$("#lightbox"),img=$("#heroImage");$("#expandImage")?.addEventListener("click",()=>{if(!img?.src)return;$("#lightboxImage").src=img.src;$("#lightboxImage").alt=img.alt;box?.classList.add("open");box?.setAttribute("aria-hidden","false")});const close=()=>{box?.classList.remove("open");box?.setAttribute("aria-hidden","true")};$("#closeLightbox")?.addEventListener("click",close);box?.addEventListener("click",e=>e.target===box&&close())}
  function newsletter(){$("#newsletterForm")?.addEventListener("submit",e=>{e.preventDefault();const i=$("#email"),m=$("#newsletterMessage");if(!i?.validity.valid){i?.focus();return}i.value="";m.textContent="You're on the list. Welcome to TrendRader."})}
  function init(){navigation();scroll();share();lightbox();newsletter();$("#footerYear")?.replaceChildren(document.createTextNode(new Date().getFullYear()));resolve().then(hydrate).catch(e=>{console.error(e);setMeta('meta[name="robots"]','noindex, follow');const b=$("#articleBody");if(b)b.innerHTML=`<div class="article-load-error"><p>This published story could not be loaded.</p><a href="../index.html">Return to TrendRader</a></div>`});}
  init();
})();
